### PR TITLE
Geocoding for the Google Map - formerly (Add files via upload)

### PR DESCRIPTION
**Pull request by TomKwee**
Fix to Add address bar to the map #5, NO geocoding yet.

### CODE REVIEW

**Review by olenakozdoba — CHANGES_REQUESTED** [review]
1. add geo-locating functionality on "Enter" key pressed
2. remove drawer toggle, we have it in the green app bar
3. work more on the look of text input to make it similar to Google map

**Comment by TomKwee** [comment]
I will address each issue with the numbers.
#1) This is now implemented with clicking on Enter key and the Location icon on the right. Code is at app.js with “document.querySelector("#searchMap_input").addEventListener('change'…”

#2) I explained this earlier about the choice to make between toolbar and paper-input. And I suggested paper-input instead of toolbar. Please review my comment on 10 days ago. Also, you can see this better if you merge the code, and then we can discuss it.

#3) I think the text input is similar to Google Map now. Perhaps it’s quicker if we talk about this. Again, if you try/test the suggested code, it is easier to visualize.

Currently I am trying to make another commit or Pull request but I cannot.

**Comment by TomKwee** [comment]
I changed 3 files, index.html, scripts/app.js, map.js. This is done by _uploading files_ onto Github onto **Tommy_branch**. You can see now there are 2 commits and 3 changed files from me, and only 1 Pull Request. This is awkward since the Pull request and files upload is not in the same group, therefore may be confusing.

I created the Tommy_branch, and you can view the updated files (above) on that branch, at least. I cannot tell whether you can compare those files from the master branch directly.

There is an extra branch Easy-Charge, probably created by me. You can delete that one.

There are matters on Github that I don't fully understand yet, and it's unlike any other source tools I have used. Therefore, I listed the 3 changes files and uploading them onto Tommy_branch.

**Comment by TomKwee** [comment]
Hi Olena,
So what is the progress of this? Should we discuss the issues verbally? I can start fixing on this Sunday, I think. I like to move forward on this. Thanks.

**Pull request closed without merging**
